language: php
sudo: true
dist: trusty

env:
  global:
    - RUN_PHPCS="no"
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.3
    - php: 7.3
      # This empty flag removes the prefer-stable switch to cause dev dependencies to be installed
      env: COMPOSER_FLAGS=""
    - php: 7.4
      env: RUN_PHPCS="yes"
    - php: 8.0
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS

script:
  - php -S 127.0.0.1:8080 & vendor/bin/phpunit --configuration phpunit.travis.xml
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards && vendor/bin/phpcs -p --report=full --extensions=php --standard=ruleset.xml src/; fi;
